version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: efk-elasticsearch
    environment:
      - node.name=elasticsearch
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - elasticsearch/esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - efk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: efk-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    restart: always
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - efk
    depends_on:
      - elasticsearch
  fluentd:
    build:
      context: ./
      dockerfile: fluentd.dockerfile
    container_name: efk-fluentd
    networks:
      - efk
    depends_on:
      - elasticsearch
    volumes:
      - type: bind
        source: ./fluentd/fluent.conf
        target: /fluentd/etc/fluent.conf
      - ./fluentd/log:/var/log
    ports:
      - 24224:24224
      - 24224:24224/udp
    expose:
      - "24224"
    restart: always
networks:
  efk:
    driver: bridge
volumes:  
  esdata:
    driver: local